version: '3'
services:

  node:
    build:
        context: .
        dockerfile: .docker/node/Dockerfile
    container_name: node
    tty: true
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: tail -f /dev/null
